//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Presentation.Delivery.UserControls.Restaurant {
    
    
    /// <summary>
    /// Restaurant class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Restaurant {
        
        /// <summary>
        /// menu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Restaurant.Presentation.Delivery.UserControls.Restaurant.Menu menu;
        
        /// <summary>
        /// resDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Restaurant.Presentation.Delivery.UserControls.Restaurant.RestaurantDetail resDetail;
        
        /// <summary>
        /// myOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Restaurant.Presentation.Delivery.UserControls.Restaurant.MyOrder myOrder;
        
        /// <summary>
        /// working control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Restaurant.Presentation.Delivery.UserControls.Restaurant.WokingHour working;
    }
}
